version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: reelmatch_postgres_db
    environment:
      POSTGRES_USER: reelmatch_user
      POSTGRES_PASSWORD: reelmatch_password
      POSTGRES_DB: reelmatch_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: