# backend/Dockerfile
FROM node:22-alpine

WORKDIR /usr/src/app

# Kopiere package.json und package-lock.json zuerst, um den Docker-Cache zu nutzen
COPY package*.json ./

# Installiere Produktionsabhängigkeiten
RUN npm ci --only=production

# Kopiere den Rest des App-Codes
COPY . .

# Exponiere den Port, auf dem der Express-Server lauscht
EXPOSE 3001

# Starte die Anwendung
CMD [ "node", "src/server.js" ]